services:
  marr_gz:
    image: marr_gz
    container_name: marr_gz
    dns: 8.8.8.8
    network_mode: "host"
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - $PWD/../marr_gz:/home/robot/marr_gz