controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

#    joint_state_broadcaster:
#      type: joint_state_broadcaster/JointStateBroadcaster

    pan_effort_controller:
      type: forward_command_controller/ForwardCommandController

    pan_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    pan_position_controller:
      type: forward_command_controller/ForwardCommandController

    tilt_effort_controller:
      type: forward_command_controller/ForwardCommandController

    tilt_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    tilt_position_controller:
      type: forward_command_controller/ForwardCommandController





pan_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: effort
    joints:
      - pantilt_pan_joint

pan_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: velocity
    joints:
      - pantilt_pan_joint

pan_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: position
    joints:
      - pantilt_pan_joint

tilt_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: effort
    joints:
      - pantilt_tilt_joint

tilt_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: velocity
    joints:
      - pantilt_tilt_joint

tilt_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: position
    joints:
      - pantilt_tilt_joint

      
